version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - falconr-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=falconr
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

    ports:
      - 25432:5432

volumes:
  falconr-data: