# Generated by Django 3.2.6 on 2021-08-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_bird_trap_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='falconer',
        ),
    ]
