# Generated by Django 3.2.6 on 2021-08-14 01:43

from django.db import migrations
import falconr.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', falconr.users.models.UserManager()),
            ],
        ),
    ]
